package main

import (
	"encoding/json"
	"fmt"
	"net/http"

	surreal "github.com/surrealdb/surrealdb.go"
)

type Config struct {
	ns     string
	db     string
	user   string
	scheme string
	pass   string
	host   string
	port   int
}

type Results struct {
	result []interface{}
	status string
	time   string
}

func restart(w http.ResponseWriter, req *http.Request) {
	configs := get_configs()

	url := configs.scheme + "://" + configs.host + ":" + fmt.Sprint(configs.port)
	db, db_err := surreal.New(url + "/rpc")

	if db_err != nil {
		fmt.Print(db_err)
	}

	_, use_err := db.Use(configs.ns, configs.db)
	if use_err != nil {
		fmt.Print(use_err)
	}

	data, d_err := db.Select("apps")
	if d_err != nil {
		fmt.Print(d_err)
	}

	// Generated by curl-to-Go: https://mholt.github.io/curl-to-go

	// curl -X POST \
	// 	 -u "root:root" \
	// 	 -H "NS: test" \
	// 	 -H "DB: test" \
	// 	 -H "Content-Type: application/json" \
	// 	 -d "SELECT * FROM person WHERE age > 18" \
	// 	 http://localhost:8000/sql
	//

	// body := strings.NewReader(`SELECT * FROM apps`)
	// req, err := http.NewRequest("POST", url+"/sql", body)
	// if err != nil {
	// 	// handle err
	// }
	// req.SetBasicAuth(configs.user, configs.pass)
	// req.Header.Set("Ns", configs.ns)
	// req.Header.Set("Db", configs.db)
	// req.Header.Set("Content-Type", "application/json")

	// resp, err := http.DefaultClient.Do(req)
	// if err != nil {
	// 	// handle err
	// }

	fmt.Println(data)

	var apps Results
	json.Unmarshal([]byte(fmt.Sprint(data)), &apps)

	fmt.Println(&apps)

	for i, s := range apps.result {
		fmt.Println(i, s)
	}

	// defer resp.Body.Close()
}

func headers(w http.ResponseWriter, req *http.Request) {

	for name, headers := range req.Header {
		for _, h := range headers {
			fmt.Fprintf(w, "%v: %v\n", name, h)
		}
	}
}

func get_configs() Config {
	configs := Config{
		user:   "root",
		pass:   "root",
		db:     "test",
		ns:     "test",
		host:   "127.0.0.1",
		scheme: "ws",
		port:   8000,
	}

	return configs
}

func main() {
	http.HandleFunc("/restart", restart)
	http.HandleFunc("/headers", headers)

	http.ListenAndServe(":8090", nil)
}
